In [259]:
import pandas as pd
import numpy as np

df=pd.read_csv("model_predictions.csv",header=None)
df.columns=["name","fc","fc_cat","cnn_cat","env_and_freq_cat","average_cat","stack_size","iteration_num"]
df=df.sample(frac=1)

In [260]:
#how often does a stacksize result in a generation?
df.groupby('stack_size').count()

,name,fc,fc_cat,cnn_cat,env_and_freq_cat,average_cat,iteration_num
stack_size,,,,,,,
1,2318,2318,2318,2318,2318,2318,2318
2,2346,2346,2346,2346,2346,2346,2346
4,411,411,411,411,411,411,411

In [268]:
#what are the group counts?
df=df[df["average_cat"]==df["cnn_cat"]]
z=df.groupby('average_cat').count()

z["name"]/np.sum(z["name"])
print(np.sum(z["name"]))

4198

In [263]:
df1=df[df["stack_size"]==1]
df2=df[df["stack_size"]==2]
df4=df[df["stack_size"]==4]

In [264]:
survey_rows=pd.concat([df1.groupby('cnn_cat').head(20),df2.groupby('cnn_cat').head(20),df4.groupby('cnn_cat').head(20)])
survey_rows

,name,fc,fc_cat,cnn_cat,env_and_freq_cat,average_cat,stack_size,iteration_num
2303,1-H6CP.wav,0.969243,hat,hat,hat,hat,1,38540
4031,1-XO3D.wav,0.980236,snare,snare,snare,snare,1,93871
614,1-7CTU.wav,0.965648,hat,rim,clap,rim,1,728
2763,1-WQQU.wav,0.816530,kick,kick,snare,kick,1,53097
2654,1-MGUR.wav,0.996767,snare,hat,hat,hat,1,49339
...,...,...,...,...,...,...,...,...
1111,4-5DLY.wav,0.937356,snare,clap,hat,snare,4,1777
882,4-AVQX.wav,0.956093,snare,clap,hat,clap,4,6154
4660,4-H7PX.wav,0.984405,snare,clap,snare,snare,4,115128
4629,4-EJLB.wav,0.845254,snare,clap,hat,hat,4,113695
1431,4-PJT6.wav,0.984305,hat,clap,hat,hat,4,11820

In [257]:
from shutil import copyfile

for n in survey_rows["name"]:
    copyfile("survey/"+n, "./filtered_survey/"+n)

sr=survey_rows.sort_values('name', ascending=True)
sr.to_csv("survey_answers.csv",index=False)

In [258]:
surv=survey_rows[["name"]].copy()
surv=surv.sort_values('name', ascending=True)
surv=surv.reset_index(drop=True)
surv["drum_category"]=""
surv.to_csv("survey.csv",index=False)